apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-tweet-app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: linux-tweet-app-container
          image: 
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi

---

apiVersion: v1
kind: Service
metadata:
  name: linux-tweet-app-service
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
